<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entities\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Services\" />
    <Content Include="**/*.feature" />
  </ItemGroup>
</Project>
